version: '3'
services:

  jenkins:
    image: 'jenkinsci/blueocean:latest'
    container_name: jenkins
    hostname: 192.168.1.103
    restart: always
    # privileged: 'true'
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - '18080:8080'
      - '50000:50000'
    env_file:
      - ./.env
    volumes:
      # - './data:/var/jenkins_home'
      - '$JENKINS_HOME/data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
